"""Build the competition submission bundle from canonical source.

``dist/submission`` is a generated package: ``main.py`` is a thin competition
input/output adapter around the canonical ``Predictor``, and the ``event_stack``
package is the same mechanically vendored canonical closure used by
``dist/inference`` (plus the isolated official-contract adapter boundary).

The official competition input/output contract is not defined by the audited
release materials, so the official mode refuses with an explicit error until a
concrete adapter is registered in
``src/pipeline/inference/competition_adapter.py``.
"""

from __future__ import annotations

import argparse
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from scripts.build_inference_distribution import build_distribution  # noqa: E402
from src.pipeline.artifacts import load_current_promoted_release  # noqa: E402


_SUBMISSION_CLOSURE_ROOTS = (
    "src.pipeline.inference.predictor",
    "src.pipeline.inference.competition_adapter",
)

_MAIN_ENTRYPOINT = '''"""Competition submission entry point for the frozen event-stack release.

Raw mode is fully supported and reproduces the canonical Predictor document.
Official competition mode is isolated behind a registered adapter; until the
official input/output contract is registered, this entry point refuses
(exit code 2) rather than guessing the wire format.
"""
from __future__ import annotations
import argparse
import json
from pathlib import Path
import sys

_ROOT = Path(__file__).resolve().parent
if str(_ROOT) not in sys.path:
    sys.path.insert(0, str(_ROOT))

from event_stack.inference import Predictor
from event_stack.inference.competition_adapter import registered_adapter


def _args(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--raw", type=Path, help="collect_data*.txt file or folder (canonical raw mode)")
    mode.add_argument("--official-input", type=Path, help="official competition input (requires a registered adapter)")
    parser.add_argument("--output", type=Path, required=True, help="destination JSON path")
    parser.add_argument("--adapter", default="official", help="registered adapter name for official mode")
    parser.add_argument("--include-timeline", action="store_true")
    parser.add_argument("--include-candidates", action="store_true")
    parser.add_argument("--device", choices=("auto", "cpu", "gpu", "cuda"), default="auto")
    return parser.parse_args(argv)


def _predict(predictor, path, *, subject_id=None, options):
    path = Path(path)
    if path.is_dir():
        return predictor.predict_folder(path, subject_id=subject_id, options=options)
    return predictor.predict_file(path, subject_id=subject_id, options=options)


def main(argv=None):
    args = _args(argv)
    try:
        manifest = json.loads((_ROOT / "manifest.json").read_text(encoding="utf-8"))
        predictor = Predictor.from_bundle(_ROOT / "models", device=args.device,
                                          run_key=str(manifest["release_run_key"]))
        options = predictor.options(include_timeline=args.include_timeline,
                                    include_candidates=args.include_candidates,
                                    device=args.device)
        if args.raw is not None:
            result = _predict(predictor, args.raw, options=options)
            args.output.write_text(json.dumps(result, ensure_ascii=False, sort_keys=True, indent=2) + "\\n", encoding="utf-8")
            return 0
        adapter = registered_adapter(args.adapter)
        raw_input, subject_id = adapter.load(args.official_input)
        result = _predict(predictor, raw_input, subject_id=subject_id, options=options)
        adapter.dump(result, args.output)
        return 0
    except NotImplementedError as exc:
        print(f"competition submission refused: {exc}", file=sys.stderr)
        return 2
    except (OSError, RuntimeError, ValueError) as exc:
        print(f"competition submission refused: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
'''

_SUBMISSION_README = """# Competition Submission Bundle

This directory is generated by `python scripts/build_submission.py` from the
promoted canonical release. Do not edit `event_stack/`, `models/`, `main.py` or
`manifest.json` manually; rebuild the package instead.

## Verifying from scratch

```bash
python -m pip install -r requirements.txt

# Raw mode smoke test (canonical raw input, canonical prediction document):
python main.py --raw path/to/collect_data1_2_3.txt --output result.json
```

`result.json` must equal the canonical `Predictor.predict_file()` document for
the same input. The package is source/model only: `manifest.json` records
SHA-256 hashes for every file and the exact source/model closures, and the build
verifies it before and after the isolated import probe.

## Official competition mode (known constraint)

The official competition input/output contract is not defined by the audited
release materials. Official mode therefore refuses explicitly until a concrete
adapter is registered:

```bash
python main.py --official-input INPUT --output OUTPUT
# exit code 2; stderr: competition submission refused: official competition
# input/output adapter is not registered
```

To enable it: implement the adapter in
`src/pipeline/inference/competition_adapter.py`, register it via
`register_adapter(...)`, and rebuild this package. No other component changes.

## Runtime ABI

Python 3.11.x with the exact pins in `requirements.txt` (from the deployment
manifest): numpy, joblib, scikit-learn, lightgbm. `--device cpu` is supported;
`--device gpu/cuda` is rejected because the promoted release has no audited CUDA
adapter.
"""


def build_submission(*, repository_root: Path, destination: Path,
                     bundle_path: Path | None = None) -> Path:
    """Atomically construct the verified competition submission package."""
    root = Path(repository_root).resolve()
    if bundle_path is None:
        release = load_current_promoted_release(root)
        bundle_path = root / "models" / "event_stack" / str(release["run_key"]) / "deployment"
    return build_distribution(
        repository_root=root, bundle_path=bundle_path, destination=destination,
        entrypoint="main.py", entrypoint_text=_MAIN_ENTRYPOINT, readme_text=_SUBMISSION_README,
        closure_roots=_SUBMISSION_CLOSURE_ROOTS,
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--bundle", type=Path, default=None)
    parser.add_argument("--destination", type=Path, default=ROOT / "dist/submission")
    args = parser.parse_args(argv)
    try:
        built = build_submission(repository_root=ROOT, destination=args.destination,
                                 bundle_path=args.bundle)
    except (OSError, RuntimeError, ValueError) as exc:
        print(f"submission build refused: {exc}", file=sys.stderr)
        return 2
    print(built)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
